import { Box, Button, Container, Divider, Typography } from '@mui/material';
import { Link, useNavigate } from 'react-router-dom';
import { FiArrowLeft, FiFileText } from 'react-icons/fi';
import { MiloLogoMark, MiloWordmark } from '../../components/MiloLogo';

const SECTIONS = [
    {
        title: '1. Agreement to Terms',
        content: `By creating an account, accessing, or using Milo ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the service. These terms apply to all visitors, registered users, and workspace members.`,
    },
    {
        title: '2. Nature of the AI Service & Advisory Disclaimer',
        content: `Milo is an autonomous personalized assistant designed to help with task prioritization, daily planning, goal breakdown, and conversational reasoning.
• Non-Professional Advice: Milo's suggestions, summaries, and briefings are generated by machine learning algorithms and do NOT constitute certified legal, medical, accounting, or professional financial advice.
• User Verification: You maintain ultimate responsibility for any decisions made, emails dispatched, or appointments scheduled following Milo recommendations.`,
    },
    {
        title: '3. User Accounts & Security',
        content: `When creating an account, you must provide accurate and complete contact information. You are solely responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized breach or access.`,
    },
    {
        title: '4. Subscriptions, Payments & Cancellations',
        content: `Certain features of Milo are offered under paid subscription tiers (e.g., Pro, Team).
• Billing Cycle: Subscriptions are billed in advance on a recurring monthly or annual basis via verified processors (Stripe or Razorpay).
• Cancellation: You may cancel your subscription at any time within your Settings > Billing panel. Your access continues until the end of your current paid billing period.
• Fair Use & Quotas: Subscriptions are subject to reasonable AI generation limits designed to maintain high server responsiveness and availability.`,
    },
    {
        title: '5. User Content & Intellectual Property',
        content: `You retain full copyright and ownership rights to all tasks, notes, goals, and personal memories stored in your Milo workspace. Milo does not assert any intellectual property claim over user-authored notes or custom agent configurations.`,
    },
    {
        title: '6. Limitation of Liability',
        content: `In no event shall Milo, its officers, or affiliates be liable for indirect, incidental, special, consequential, or punitive damages resulting from your use of or inability to use the service, including data loss or work disruption.`,
    },
];

const TermsOfService = () => {
    const nav = useNavigate();

    return (
        <Box sx={{ minHeight: '100dvh', bgcolor: 'var(--bg)', color: 'var(--ink)' }}>
            {/* Top Navigation Bar */}
            <Box
                sx={{
                    borderBottom: '1px solid var(--border)',
                    bgcolor: 'var(--surface)',
                    position: 'sticky',
                    top: 0,
                    zIndex: 10,
                    px: { xs: 2, sm: 4 },
                    py: 1.8,
                }}
            >
                <Box sx={{ maxWidth: 1000, mx: 'auto', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <MiloLogoMark size={28} />
                        <MiloWordmark size={18} />
                    </Box>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                        <Link to="/privacy" style={{ fontSize: '13px', color: 'var(--text-secondary)', textDecoration: 'none', fontWeight: 500 }}>
                            Privacy Policy
                        </Link>
                        <Button
                            variant="outlined"
                            size="small"
                            startIcon={<FiArrowLeft size={14} />}
                            onClick={() => nav(-1)}
                            sx={{ borderRadius: '7px', textTransform: 'none', fontSize: '13px', color: 'var(--ink)', borderColor: 'var(--border-strong)' }}
                        >
                            Back
                        </Button>
                    </Box>
                </Box>
            </Box>

            {/* Document Body */}
            <Container maxWidth="md" sx={{ py: { xs: 4, sm: 6 } }}>
                <Box sx={{ mb: 4 }}>
                    <Box sx={{ display: 'inline-flex', alignItems: 'center', gap: 0.8, px: 1.4, py: 0.5, borderRadius: '20px', bgcolor: 'var(--accent-soft)', color: 'var(--accent)', fontSize: '12px', fontWeight: 700, mb: 1.5 }}>
                        <FiFileText size={14} /> TERMS OF SERVICE
                    </Box>
                    <Typography sx={{ fontWeight: 800, fontSize: { xs: '28px', sm: '36px' }, letterSpacing: '-0.03em', mb: 1, color: 'var(--ink)' }}>
                        Terms of Service
                    </Typography>
                    <Typography sx={{ fontSize: '14px', color: 'var(--text-secondary)' }}>
                        Effective date: October 2026 • Please read carefully before using the Milo productivity suite.
                    </Typography>
                </Box>

                {/* Content Sections */}
                <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3.5 }}>
                    {SECTIONS.map((sec, i) => (
                        <Box key={i} sx={{ bgcolor: 'var(--surface)', p: { xs: 2.5, sm: 3 }, borderRadius: '12px', border: '1px solid var(--border)' }}>
                            <Typography sx={{ fontWeight: 700, fontSize: '17px', color: 'var(--ink)', mb: 1.4 }}>
                                {sec.title}
                            </Typography>
                            <Typography sx={{ fontSize: '13.5px', color: 'var(--ink-soft)', lineHeight: 1.7, whiteSpace: 'pre-line' }}>
                                {sec.content}
                            </Typography>
                        </Box>
                    ))}
                </Box>

                <Divider sx={{ my: 4, borderColor: 'var(--border)' }} />

                <Box sx={{ textAlign: 'center', py: 2 }}>
                    <Typography sx={{ fontSize: '12.5px', color: 'var(--text-muted)' }}>
                        © 2026 Milo AI Systems Inc. All rights reserved.
                    </Typography>
                </Box>
            </Container>
        </Box>
    );
};

export default TermsOfService;
